name: CI - Build, Test & Coverage

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y build-essential cmake lcov bc

      - name: Build with coverage
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_CXX_FLAGS="--coverage" \
            -DCMAKE_C_FLAGS="--coverage"
          make -j2

      - name: Run tests
        run: cd build && ./amplitron-tests

      - name: Generate coverage
        run: |
          cd build
          lcov --capture --directory . --output-file coverage.info
          lcov --remove coverage.info '/usr/*' '*/external/*' '*/tests/*' \
            --output-file filtered.info

      - name: Check coverage threshold
        run: |
          COVERAGE=$(lcov --summary filtered.info | grep lines | awk '{print $4}' | tr -d '%')
          echo "Coverage = $COVERAGE"
          if (( $(echo "$COVERAGE < 60" | bc -l) )); then
            echo "Coverage below 60%"
            exit 1
          fi

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: build/filtered.info

      - name: PR Coverage Comment
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: coverage
          message: |
             Coverage Report Generated

            ✔ Build & tests completed
            ✔ Coverage file created

            👉 Full details Codecov par check karo

      
      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: build/filtered.info
          fail_ci_if_error: false