name: Coverage CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  coverage-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            lcov gcovr cmake g++ \
            libgl1-mesa-dev \
            mesa-common-dev \
            freeglut3-dev \
            libglu1-mesa-dev \
            libsdl2-dev \
            portaudio19-dev \
            librtmidi-dev \
            pkg-config

      - name: Setup External Dependencies
        run: |
          set -e

          mkdir -p external external/kiss_fft

          git clone --depth 1 https://github.com/ocornut/imgui.git external/imgui

          curl -fsSL -o external/nanosvg.h https://raw.githubusercontent.com/memononen/nanosvg/master/src/nanosvg.h
          curl -fsSL -o external/nanosvgrast.h https://raw.githubusercontent.com/memononen/nanosvg/master/src/nanosvgrast.h
          curl -fsSL -o external/dr_wav.h https://raw.githubusercontent.com/mackron/dr_libs/master/dr_wav.h

          curl -fsSL -o external/kiss_fft/kiss_fft.h https://raw.githubusercontent.com/mborgerding/kissfft/master/kiss_fft.h
          curl -fsSL -o external/kiss_fft/kiss_fft.c https://raw.githubusercontent.com/mborgerding/kissfft/master/kiss_fft.c
          curl -fsSL -o external/kiss_fft/_kiss_fft_guts.h https://raw.githubusercontent.com/mborgerding/kissfft/master/_kiss_fft_guts.h
          curl -fsSL -o external/kiss_fft/kiss_fft_log.h https://raw.githubusercontent.com/mborgerding/kissfft/master/kiss_fft_log.h

      - name: Configure project
        run: |
          cmake -S . -B build -DENABLE_COVERAGE=ON -DCMAKE_BUILD_TYPE=Debug

      - name: Build project
        run: |
          cmake --build build -j

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure

      - name: Generate coverage
        run: |
          cd build
          lcov --capture --directory . --output-file coverage.info
          lcov --remove coverage.info '/usr/*' '*/external/*' '*/tests/*' \
            --output-file filtered.info

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: build/filtered.info